name: Execute unit test for frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "vitest"
        working-directory: ./frontend
        run: npm run test
